name: Test Automation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.16.0, 18.12.0 ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: borales/actions-yarn@v3.0.0
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn build
      - run: yarn test
